#!/bin/sh

mkdir /proc /sys
mount /proc
mount /sys
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

mount -t debugfs debugfs /sys/kernel/debug

for x in $(cat /proc/cmdline)
do
	case $x in
		eimt.nfsaddr=*)
		NFS_ADDRESS="${x//eimt.nfsaddr=}"
		;;
	esac
done

if [ -z "$NFS_ADDRESS" ]
then
	echo "Error: NFS address not set!"
	exit 1
fi

udhcpc -n

mkdir /mnt /tmp
mount -o nolock,ro,hard,intr,vers=3 -t nfs $NFS_ADDRESS /mnt

echo "Starting test"
cd /mnt
./test_init
echo "Test completed, shutting down"
poweroff -f
