#!/bin/sh

NFS_ADDRESS=192.168.10.1:/home/mperttunen/upstream/testenv

mkdir /proc /sys
mount /proc
mount /sys
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

mount -t debugfs debugfs /sys/kernel/debug

udhcpc -n

mkdir /mnt /tmp
mount -o nolock,ro,hard,intr,vers=3 -t nfs $NFS_ADDRESS /mnt

echo "Starting test"
cd /mnt
./test_init
echo "Test completed, shutting down"
poweroff -f
